### ISSUE TITLE
Support all reset

### ISSUE THREAD

**Issue by jonathanKingston** [cssnext/cssnext#110]
It seems a useful reset to have:
http://www.w3.org/TR/css-cascade-3/#all-shorthand

The generated syntax may however be very heavyweight listing all rules; it may be worth allowing some level of customisation in the generated output just to reset a chosen list if there is one specified.

Thoughts?

**Comment by MoOx** [comment]
Sure this will be generating a looot of css. But if it's doable with not ?
Maybe we can add this under a flag so user only enable that kind of huge output option by hand ?
That said, since css vocabulary is pretty short, I guess gzip will do an amazing job on that kind of output, am I right ?

**Comment by jonathanKingston** [comment]
Yup thats why I think we should offer up the ability to change which properties it would output (I suspect most people care about resetting very few properties in reality).

Not sure what you meant by this sentence sorry:
>But if it's doable with not ?

I guess we can slap in all the defaults and see how it goes with gzip (as you say it should work very well).

**Comment by MoOx** [comment]
If we can do it, we should do it :)
We can make this as a plugin that accept some options, like most plugins already :)

**Comment by MoOx** [comment]
Closing due to lack of interest.
