### ISSUE TITLE
website domain

### ISSUE THREAD

**Issue by MoOx** [cssnext/cssnext#113]
.com ?
.io ?
.ninja ?

Please drop your ideas or vote for the one you would like to see :)

**Comment by magsout** [comment]
.io :+1:

**Comment by jonathanKingston** [comment]
.org might be more relevant again looks dated but depends on the driving image you want to give mostly. (lesscss and eslint are org)

.dev and others will drop soon that might be more relevant etc but I would always err on what most people type by default.

**Comment by MoOx** [comment]
# Watchers, please give your opinion on this

:)

**Comment by watilde** [comment]
.io +1

**Comment by kud** [comment]
.io but it's not so cheap.

**Comment by dhoko** [comment]
.fr :trollface: 

.io +1

**Comment by simonsmith** [comment]
.io +1

**Comment by neilhem** [comment]
:+1: for .io

**Comment by zoontek** [comment]
.io :+1:

**Comment by bloodyowl** [comment]
.technology

**Comment by jonathanKingston** [comment]
.style goes live today

**Comment by Sacripant** [comment]
.bio  because it's pur CSS, no SASS or other chimical fertilizer
.tools because it's a tools ^^
.style because style sheets
.ws for website
.tech (coming soon)
.today because u can use Css next today (no found .now)

**Comment by MoOx** [comment]
.style are nice, but 145€ ! Ouch.
I guess I will go for .io...

**Comment by MoOx** [comment]
.style will have the same price when the state change to GoLive. In some hours :)

**Comment by Macxim** [comment]
I'd go for .style too.

**Comment by simonsmith** [comment]
We need a `.next`
