### ISSUE TITLE
Add a link to "there is not css4"

### ISSUE THREAD

**Issue by MoOx** [cssnext/cssnext#119]
http://www.xanthir.com/b4Ko0

**Comment by Macxim** [comment]
:+1:

**Comment by joshuahiggins** [comment]
+1. 

CSS3 as a term already confuses new developer's understanding of the language. Mentioning CSS4+ will only add more confusion. 

Mention of non-existent language specs should be removed and cssnext should reference which level of individual modules it supports. As an example, filter is only level 1.
