### ISSUE TITLE
Check out why code climate is yelling

### ISSUE THREAD

**Issue by MoOx** [cssnext/cssnext#121]
Since we setup eslint, code climate is not happy

https://codeclimate.com/github/cssnext/cssnext

We need to fix that.

**Comment by jonathanKingston** [comment]
Code climate looks at JSHint files which were removed with ESLint.

http://docs.codeclimate.com/article/241-can-i-customize-how-javascript-linting-is-performed

So add the file back in perhaps?

**Comment by MoOx** [comment]
I see that. So I will probably drop code climate since I don't want to keep jshint too (also: #101)

**Comment by MoOx** [comment]
Codeclimate badge has been removed. We use eslint already, no need for another thing.
