### ISSUE TITLE
Watching files with multiple imports is broken

### ISSUE THREAD

**Issue by klaemo** [cssnext/cssnext#123]
Hey,
it seems as if files with multiple imports don't get watched properly.

**index.css**
```css
@import "./one.css";
@import "./two.css";
```

**one.css**
```css
h1 {
  color: red;
}
```

**two.css**
```css
h2 {
  color: blue;
}
```

running cssnext does compile the files correctly, but doesn't watch
```bash
$ cssnext --watch -v index.css bundle.css
[11:52:27] Output written /Users/clemens/Projects/cssnext-bug/bundle.css
```

commenting out one `@import` yields the expected result:

```bash
$ cssnext --watch -v index.css bundle.css
[11:52:40] Output written /Users/clemens/Projects/cssnext-bug/bundle.css
[11:52:40] Watching /Users/clemens/Projects/cssnext-bug/index.css
```

`OSX 10.10.3`
cssnext: `1.4.0`
iojs: `1.8.1`

Thank you! :)

**Comment by MoOx** [comment]
> running cssnext does compile the files correctly, but doesn't watch

I am not sure on what you are saying since right after that you say that commenting an import is making a change.

Do you expect to get a verbose ouput that is saying that index.css is watched in the first place ?

```console
$ cssnext --watch -v index.css bundle.css
[11:52:27] Output written /Users/clemens/Projects/cssnext-bug/bundle.css
[11:52:40] Watching /Users/clemens/Projects/cssnext-bug/index.css
```

And then when you comment an import you get

```console
$ cssnext --watch -v index.css bundle.css
[11:52:27] Output written /Users/clemens/Projects/cssnext-bug/bundle.css
[11:52:40] Watching /Users/clemens/Projects/cssnext-bug/index.css
[11:52:47] Output written /Users/clemens/Projects/cssnext-bug/bundle.css
```

Is that what you would expect ?

**Comment by klaemo** [comment]
No, the first one (with both imports) doesn't pick up any changes at all.

For the second one I restarted `cssnext`. 

One import === changes get detected and recompiled.
Multiple imports === changes **don't** get detected and nothing gets recompiled

**Comment by MoOx** [comment]
Ok I will take a deeper look then, cause "it works for me™"  on one project. Thanks for reporting !

**Comment by klaemo** [comment]
The weird thing is: it used to work for me too :D then I reinstalled all my modules from scratch...

Taking a look at the code: `watcher.on("ready")` doesn't fire when there are multiple imports. I'll investigate further.

**Comment by jonathanong** [comment]
hmmm i think i'm seeing the same issue...

**Comment by iantearle** [comment]
Also seeing this.

**Comment by MoOx** [comment]
Looks like a chokidar bug https://github.com/paulmillr/chokidar/issues/288#issuecomment-123570165
I will push a workaround (by not relying on ready event).

**Comment by MoOx** [comment]
I will release this fix tomorrow morning (in 8 hours).
Meanwhile you can try it by installing cssnext from git (here are the installation instructions https://github.com/cssnext/cssnext/commit/1eaca8309b08cce4e5f189b8a411b1f5f572a52d)

Should be better now. Sorry for the delay guys.

**Comment by klaemo** [comment]
Thank you, Maxime 🎉
