### ISSUE TITLE
Use CanIUse data and browserslist to enable/disable plugins

### ISSUE THREAD

**Issue by ai** [cssnext/cssnext#125]
[Stylecow](http://stylecow.github.io/) vs. PostCSS text:

> The plugin of the previous example (postcss-vmin) only makes sense if we want to add support for explorer 9. In postcss, you have to decide which plugins you have to use, according with the browser support you need (with the exception of some plugins like autoprefixer). In stylecow, the plugins can have the browser support, so, if you use the vmin plugin but your minimum suport is explorer 10, this plugin wont be executed.

If cssnext will use Can I Use as Autoprefixer we will bit this feature.

**Comment by MoOx** [comment]
It's already possible since 1.x.

https://github.com/cssnext/cssnext#nodejs-options

https://github.com/cssnext/cssnext/blob/78832083bb0b293294853d9957e1c21e8d539a4d/index.js#L12

**Comment by ai** [comment]
Awesome!

Second question: does plugins order matter in `postcss-import`?

**Comment by MoOx** [comment]
postcss-import is executed before anything else, so I don't see any possible issue.
