### ISSUE TITLE
NonCompiled Comments.

### ISSUE THREAD

**Issue by DavidBrear** [cssnext/cssnext#134]
I believe it would be really nice to be able to specify comments that are not compiled into the CSS. Somewhat like what SASS allows you to do with the ```//``` comment.

**Comment by Macxim** [comment]
Relevant https://github.com/cssnext/cssnext/issues/76

**Comment by MoOx** [comment]
cssnext aims to support specs only for now. No spec/draft/proposal, no implementation :/
