### ISSUE TITLE
Is there a cssnext for use on the web coming up?

### ISSUE THREAD

**Issue by enociz** [cssnext/cssnext#143]
The preprocessor Less has a version of itself which allows it to be used in the browser mainly for testing purposes. Is this a feature we can expect for cssnext? If it was implemented, a lot of time in the terminal would be saved (unless you 'watch'ed the file).

**Comment by alp82** [comment]
That's the point of watchers. Why do you prefer to not use them?

**Comment by corysimmons** [comment]
@alp82 :+1:

**Comment by MoOx** [comment]
I think we should encourage this kind of usage. If the community ask for it we might have a second thought about that.

**Comment by MoOx** [comment]
Oups sorry. I meant "not encourage". Closing for now.

**Comment by enociz** [comment]
Sure, I just thought of bringing it uo
