### ISSUE TITLE
Error: Cannot find module 'lodash._basebind'

### ISSUE THREAD

**Issue by koistya** [cssnext/cssnext#151]
```js
var cssnext = require('cssnext');          
```

```
Error: Cannot find module 'lodash._basebind'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (.\node_modules\cssnext\node_modules\caniuse-api\node_modules\lodash.uniq\node_modules\lodash.createcallback\node_modules\lodash._basecreatecallback\node_modules\lodash.bind\node_modules\lodash._createwrapper\index.js:9:16)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
```

**Comment by MoOx** [comment]
@Nyalab any idea about this ?
@koistya can you clean npm cache & try again please ? It's weird to get this only now.

**Comment by Nyalab** [comment]
i am looking into it today, thanks for the report @koistya

**Comment by MoOx** [comment]
@koistya any change with a fresh install ?

**Comment by koistya** [comment]
I'm away from my desktop, will try fresh install on Monday.

**Comment by awayken** [comment]
Not sure if this is related, but I updated to the latest iojs yesterday to 2.2.1 and started to have issues like this. I was technically using the gulp-cssnext module, but I think it was the same error. I downgraded back to iojs 2.0.2 and everything worked fine again.

I'm running on Windows 8.1 using iojs 64-bit but haven't looked around to see if other people had issues when they upgraded.

**Comment by MoOx** [comment]
I will consider it was a temporary issue since nobody came here to report as well. Please let me know if you still have the issue.

**Comment by koistya** [comment]
Having this issue with a fresh install as well.

```
io.js 2.3.0, npm 2.11.3, postcss 4.1.12, cssnext 1.7.1, OS Win 8.1 x64
```

**Comment by koistya** [comment]
Maybe it has something to do with `babel/register`?

**Comment by MoOx** [comment]
Please clear your local npm cache & reinstall and then let us know what happen :)

**Comment by koistya** [comment]
Clearing local npm cache doesn't help

**Comment by koistya** [comment]
@MoOx the problem is that when I install `cssnext`, node_modules/cssnext/node_modules/caniuse-api contains `lodash.uniq` 2.4.1. If it will be a more recent version, this issue will be resolved.

**Comment by MoOx** [comment]
caniuse-api 1.3.2 should fix that.

**Comment by koistya** [comment]
Yep, fixed.
