### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by Semigradsky** [cssnext/cssnext#154]
It would be great to get a new version [with updated `postcss-custom-selectors`](https://github.com/cssnext/cssnext/commit/27efd385b7d3809021fefb563119e5e5a46e1d27) :smile:

**Comment by MoOx** [comment]
1.7.0 will be out on Wednesday.

**Comment by Semigradsky** [comment]
Great! Thanks :+1:

**Comment by MoOx** [comment]
Thanks for your patience :)
