### ISSUE TITLE
Consider adding postcss-flexbugs-fixes

### ISSUE THREAD

**Issue by MoOx** [cssnext/cssnext#158]
What do you think about that guys ?

https://github.com/luisrudge/postcss-flexbugs-fixes

Would be nice to have it ?

**Comment by lionelB** [comment]
For now it's ok since it only fix bug8, but some workarounds (bug3) may add rules and potentially can override user's rules.

**Comment by MoOx** [comment]
We might enhance this plugin so it add warnings about those potential collisions.
poke @luisrudge

**Comment by lionelB** [comment]
and let the user select which bug the want to fix

**Comment by luisrudge** [comment]
Oh! I forgot about that. I still have to publish the plugin to npm, but I'd like to add more rules before doing so.

**Comment by philipwalton** [comment]
I'm just seeing this plugin for the first time, and I already see some problems with it. I filed https://github.com/luisrudge/postcss-flexbugs-fixes/issues/18 and https://github.com/luisrudge/postcss-flexbugs-fixes/issues/19.

Assuming these are fixed I think it'd be OK to add, but my concern is it might make users think they don't have to worry about these issues at all anymore, when in fact many of them can only be solved in HTML-land.

Also, some of them (e.g. 7) won't be able to catch all cases, arguably most cases even. Consider this example:

```css
* {
  box-sizing: border-box;
}

.box {
  flex: 1 1 50%;
  padding: 1em;
}
```

cssnext cannot always know what elements have their box model set to `border-box`.

**Comment by luisrudge** [comment]
Yeah @philipwalton. I thought about that too. Most of the stuff are too context dependent, so you need to check html to see if that'll happen or not. One thing we discussed in an issue, is to emit warnings about other bugs, but I don't like that idea either.

**Comment by MoOx** [comment]
Good points guys.

Warnings can help at least https://github.com/luisrudge/postcss-flexbugs-fixes/issues/17

**Comment by MoOx** [comment]
I don't think it's a good idea anymore.
