### ISSUE TITLE
Rename from/to options to source/dest ?

### ISSUE THREAD

**Issue by MoOx** [cssnext/cssnext#160]
I always found `from` & `to` option where pretty shitty and I am not sure we should keep them.
We might introduce this change in a major release.

Any thoughts ?

**Comment by ben-eb** [comment]
Where possible it would be good to be consistent with what the rest of the PostCSS ecosystem is doing. I think any such change should be in PostCSS itself to maintain that consistency.

**Comment by MoOx** [comment]
These options are only relevant if you are using cssnext directly, not through postcss. So not sure if it's a requirement. But if @ai is open to this kind of improvement, why not.

**Comment by ben-eb** [comment]
Yep, but it is nicer if all of our modules use the same options for source maps; so that if a user of a PostCSS module wants source maps, she doesn't have to apply different options when wanting to use cssnext instead. :smile:

**Comment by MoOx** [comment]
I don't consider cssnext as a postcss plugin (mostly because I think most people should not use postcss directly - like babel user that don't use acorn directly).
I have plan for v2 to change it's API and this issue will probably be part of it.

**Comment by ai** [comment]
@MoOx I understand you, but without a main PostCSS runner there will not be a way for small and new plugins for developer. We will stagnation.

**Comment by MoOx** [comment]
I am not sure about what you are saying @ai.
Anyway, would you consider renaming from/to to source/destination in the next major release ?

**Comment by ai** [comment]
My idea is that if user use gulp-postcss, instead of postcss autoprefixer or gulp-cssnext, he can add also many other small PostCSS plugins, like postcss-data-packer. So market will be open for new ideas. With gulp-autoprefixer it is psychology more difficult to add new plugin for user.

**Comment by MoOx** [comment]
cssnext now have a plugin option to pipe others plugins :)

**Comment by ai** [comment]
We can rename it, of course.

But why they are better? It is only question of taste our there is any objective benefits.

What Babel uses?

**Comment by MoOx** [comment]
Babel don't have this kind of options.
But src/source and dest/destination are much more common than from/to in a lot of open source projects (metalsmith, gulp, grunt...).

**Comment by MoOx** [comment]
Should be a postcss issue.
