### ISSUE TITLE
postcss-log-warnings deprecated in favor of postcss-reporter

### ISSUE THREAD

**Issue by jedmao** [cssnext/cssnext#162]
The author of [postcss-log-warnings](https://github.com/davidtheclark/postcss-log-warnings) has deprecated it in favor of [postcss-reporter](https://github.com/postcss/postcss-reporter). Perhaps we should follow suit?

**Comment by magsout** [comment]
Yes we should

**Comment by MoOx** [comment]
@jedmao I originally asked for [a renaming of the 2 modules that are used](https://github.com/postcss/postcss-messages/issues/17#issuecomment-109579949) so yeah, I will update that :)
