### ISSUE TITLE
cssnext CLI throws parsing error for rgba()

### ISSUE THREAD

**Issue by trippersham** [cssnext/cssnext#167]
Transpiling the Basscss optional modules and the cssnext CLI is throwing the following error for 9 of the modules:
```
cssnext encounters an error:

Unable to parse color from string "rgba(#000,.0625)"
undefined

If this error looks like a bug, please report it here:
❯ https://github.com/cssnext/cssnext/issues
```

Same exact CSS4 works in the playground, but is failing in the CLI. The following Basscss modules are failing:
https://github.com/basscss/basscss-color-buttons
https://github.com/basscss/basscss-button-blue
https://github.com/basscss/basscss-button-blue-outline
https://github.com/basscss/basscss-button-gray
https://github.com/basscss/basscss-button-light-gray
https://github.com/basscss/basscss-button-red
https://github.com/basscss/basscss-button-nav-light
https://github.com/basscss/basscss-button-nav-dark
https://github.com/basscss/basscss-button-nav-tab

**Comment by MoOx** [comment]
That might "work" in the playground:

```css
body{
  color: rgba(#000,.0625);
}
```

This is creating an error because color function is invoked to parsed an modify the invalid color

```css
body{
  color:color(rgba(#000,.0625) a(.1));
}
```

I guess you are getting the error from something similar.

This is not valid CSS. That's why it doesn't work. You should ask @jxnblk to use color function instead of this invalid code :) (eg: `color(#000 a(.0625)`).

**Comment by jxnblk** [comment]
@trippersham It looks like you're using some older modules, which used to use Rework and require https://github.com/reworkcss/rework-plugin-colors for compilation (which doesn't use by-the-spec syntax). 

Feel free to open an issue on the relevant Basscss repos.
