### ISSUE TITLE
1.8.0 warns for every selector I use if imports are involved

### ISSUE THREAD

**Issue by topaxi** [cssnext/cssnext#171]
index.css:
```css
@import 'foo.css';

.bar {
  color: blue;
}
```

foo.css:
```css
.foo {
  color: blue;
}
```

Shell or any build tool:
```css
$ cssnext index.css
Warning: The selector '.foo' is undefined in CSS!
Warning: The selector '.bar' is undefined in CSS!
.foo {
  color: blue;
}

.bar {
  color: blue;
}
```

Tested using io.js 2.3.1

**Comment by klaemo** [comment]
yep, same here.

**Comment by MoOx** [comment]
Hum... Maybe related to recent update from postcss-custom-selectors by @yisibl ?

**Comment by MoOx** [comment]
https://github.com/postcss/postcss-custom-selectors/issues/22

**Comment by MoOx** [comment]
A fix has been proposed https://github.com/postcss/postcss-custom-selectors/pull/23
Hope it will be merged and released asap.

**Comment by MoOx** [comment]
Please reinstall cssnext to get the latest version of postcss-custom-selectors, fix has been merged an released.
