### ISSUE TITLE
cssnext throwing error for missing vars when used with postcss-custom-properties

### ISSUE THREAD

**Issue by hellosmithy** [cssnext/cssnext#176]
Given a config:

```
cssnext: {
	browsers: "last 2 versions",
	plugins: [
		/* ... other plugins ...*/
		require('postcss-custom-properties')({
			variables: {
				'--background': 'red'
			},
			appendVariables: true
		})
	]
}
```

If I use `--background` variable in my css, then cssnext complains that the variable is "undefined and used without a fallback" even though the the variable is defined and in fact is being applied in the rendered CSS.

I assume this is because cssnext is processing before passing off to the other plugins. Shouldn't we be able to control the order of execution (maybe this is already possible and I'm missing something)?

**Comment by MoOx** [comment]
`postcss-custom-properties` is already included in cssnext.
Please read the doc http://cssnext.io/usage/#features you should get tour anwser. Otherwise, please use the Support chat.
