### ISSUE TITLE
Is there a way to define the autoprefixer setup in the CSS?

### ISSUE THREAD

**Issue by dschissler** [cssnext/cssnext#179]
I first started on `autoprefixer-core` and I was able to use the line `@autoprefixer(browsers: ['last 2 versions']);` in the CSS but this doesn't seem to work with cssnext.  Is there a way to do this in the CSS without setting this globally in my webpack setup?  I need this because there will be at least two profiles in my project.

**Comment by MoOx** [comment]
It looks like a cssnext-loader issue, am I right?

**Comment by dschissler** [comment]
Possibly but its relevant here too since specifically I want to define this in CSS and it is possible to do with just the autoprefixer-core plugin that is a part of cssnext.  I want to be able to define this per-CSS file it doesn't make sense to do it at a lower level in JS because I'd have to do a bunch of complicated switching for my different profiles.  I know that this functionality exists in straight autoprefixer-core and I'm wondering what is going on that cssnext doesn't parse this feature.  I'm on day 1 of R&D.

**Comment by dschissler** [comment]
Also I'm using `postcss-loader` with the `cssnext` plugin so that I have room to grow.

**Comment by MoOx** [comment]
cssnext `browser` options is supposed to work the same as autoprefixer one. It's a string and it's even passed to autoprefixer too (cssnext include autoprefixer).
Can you provide more code to show what you want to do?

Btw, cssnext have a `plugins` option to add more plugins after cssnext list.

**Comment by MoOx** [comment]
cssnext propagate the option to autoprefixer https://github.com/cssnext/cssnext/blob/fa5979a76e497ce8cc350ee31437e12f2e265e70/src/index.js#L46-L61 (also some tests should confirm that's working).

**Comment by dschissler** [comment]
I want to do this in CSS: `@use autoprefixer(browsers: ['last 2 versions']);` instead of this in javascript: `browsers: ['last 1 versions'],`.

**Comment by dschissler** [comment]
The Javascript options are working, that isn't an issue.  I first started with `autoprefixer-core` directly and an example used this CSS option and it appeared to work/parse it but `cssnext` ignores it.  In my case the CSS setup is better.

**Comment by MoOx** [comment]
OH. I see, so I guess you are using `postcss-use`. I don't see how it should not work.
What you are requesting is not really clear. postcss-use include plugin after the initial postcss instance, so now sure how it will behave... poke @ben-eb

**Comment by dschissler** [comment]
Ok, I'll try that now.  I don't see that I ever installed that module but perhaps that is it.

**Comment by ben-eb** [comment]
I would have thought that its usage would be no different with cssnext.

**Comment by MoOx** [comment]
It should not.

**Comment by dschissler** [comment]
Thanks everyone.  I was never using `postcss-use` so it must have not been parsing it out of the CSS, although I thought that it was.  So its another issues.
