### ISSUE TITLE
cssnext v2 roadmap (BREAKING CHANGES are welcome)

### ISSUE THREAD

**Issue by MoOx** [cssnext/cssnext#185]
**Drop you ideas here if you are thinking about some breaking changes !**

- get rid of the simple api that can return a string OR an object depending on your config in favor or the async api `cssnext(config).process(input[, runtimeOptions])` offered by PostCSS 4.2+

Do not hesitate to drop anything here, there is no bad ideas, only ideas ;)

**Comment by klaemo** [comment]
fixing file watching would be nice

**Comment by topaxi** [comment]
Not a big one but will the process method return a promise?

**Comment by ben-eb** [comment]
@topaxi It supports both sync and async usage.

https://github.com/postcss/postcss/commit/86eeb0c3ef64a47c3c1d26fdd6e37b7dbd7bd2e1

**Comment by topaxi** [comment]
@ben-eb nice! :)

**Comment by jonathanong** [comment]
yeah i really need watching. it's embarrassing to recommend cssnext to coworkers when watching doesn't even work.

**Comment by MoOx** [comment]
@jonathanong @klaemo watcher issue is the next thing on my todo list. Except a patch soon.

**Comment by MoOx** [comment]
Closing for now since I am not even sure this project will make sense in a near future.
Related:
- https://github.com/babel/babel/issues/2168
- https://github.com/postcss/postcss/issues/477
