### ISSUE TITLE
Escaping string for variable value.

### ISSUE THREAD

**Issue by mikedidthis** [cssnext/cssnext#197]
Firstly, thanks for all the hard work!

Not an issue, more a question. Is it possible to use any arbitrary string as variable value? An example from lesscss:

```
.weird-element {
  content: ~"^//* some horrible but needed css hack";
}
```

My use case:

```
--heading-font-family: ~"string here";
```

Output:

```
--heading-font-family: string here;
```

I totally understand this may not be possible and that cssnext isn't lesscss. 

:cake:

**Comment by MoOx** [comment]
You should be able to escape css with \, this it not related to string or something.

example of valid css classname: `.stuff\@md`.

**Comment by mikedidthis** [comment]
I may have picked the wrong wording. I want to use any string for the variable value, this may not be a css value, for instance:

```
--heading-font-family: <?php /* code */ ?>;
```

Thanks for the response, I appreciate this maybe out of the scope of cssnext.

**Comment by MoOx** [comment]
You can in theory use any value that respect css syntax. cssnext use postcss so be sure to provide something that the parser accept. Or you can try to add your own parser, but indeed, that's not the scope of cssnext.
