### ISSUE TITLE
@import doesn't work with postcss@5.0.0 in Webpack

### ISSUE THREAD

**Issue by nthtran** [cssnext/cssnext#198]
`@import` results in an error when built with Webpack, `cssnext` and the latest `postcss-loader@0.6.0`. The previous version of `postcss-loader` works fine however.

**Comment by MoOx** [comment]
postcss-import is not compatible with postcss 5.x yet.

**Comment by MoOx** [comment]
It is now. But cssnext is not yet. See #202
