### ISSUE TITLE
Add support for :blank pseudo-class

### ISSUE THREAD

**Issue by DoronBrayer** [cssnext/cssnext#204]
Hey, I love this postprocessor! Great job!

Please add support for the [:`blank` pseudo-class](http://www.w3.org/TR/selectors4/#blank-pseudo).
The `:blank` pseudo-class is kind of like the prettier cousin of `:empty`.
The `:blank` pseudo-class will select an element as long as it has no text and no other child elements, regardless of white space. So it could contain white space, line breaks, etc., and it would still qualify.

**Comment by MoOx** [comment]
This require some knowledges about the actual DOM tree, so it's impossible from cssnext side (preprocessor, no client side polyfill involved). Sorry.
