### ISSUE TITLE
Add support for :has pseudo-class

### ISSUE THREAD

**Issue by DoronBrayer** [cssnext/cssnext#205]
Hey, I love this postprocessor! Great job!

Please add support for the [:`has` pseudo-class](https://drafts.csswg.org/selectors/#relational).
The `:has` pseudo-class is similar to [jQuery’s .has()](https://api.jquery.com/has/) but with some broader abilities.
This feature will boost the CSS immensely.

**Comment by MoOx** [comment]
Same anwser has https://github.com/cssnext/cssnext/issues/204#issuecomment-135318751
