### ISSUE TITLE
CLI - compress doesn't remove comments

### ISSUE THREAD

**Issue by cedriceberhardt** [cssnext/cssnext#206]
When using the compress option, the comments are not removed and it keeps the line breaks as well. Looks weird because cssnano alone works perfectly - both v2.6.1.

**Comment by MoOx** [comment]
It's seems that postcss-discard-comments is not run for a reason I don't understand. I got this issue yesterday but was too lazy to check out why. @ben-eb any idea why ?

**Comment by ben-eb** [comment]
I think it's a PostCSS 5 issue.

https://github.com/ben-eb/cssnano/issues/51

**Comment by cedriceberhardt** [comment]
PostCSS 4 looks like to be used for both packages. And I tried with cssnano too and I didn't have problems. It worked well. No comments, no break lines. I took the first example in the cssnano homepage.

**Comment by ben-eb** [comment]
Alright, I'll have a look into it. :smiley:

**Comment by ben-eb** [comment]
Should be fixed now by https://github.com/postcss/postcss-filter-plugins/commit/1115a91f2314dff77402c12d567e48f61e08ab20

**Comment by MoOx** [comment]
Cool, thanks!

**Comment by cedriceberhardt** [comment]
:+1:
