### ISSUE TITLE
cli plugin option

### ISSUE THREAD

**Issue by lgersman** [cssnext/cssnext#211]
hello,

i want to use a postcss plugin (https://github.com/jonathanong/postcss-prefix-selector to be concrete) together with cssnext using cssnext cli interface. 

the cssnext documentation states that postcss plugins can be used together with an example written directly in js. i would like to use it from the commandline.

is it already implemented ?

any ideas how it can be done ?

kind regards,

lars

**Comment by MoOx** [comment]
cli interface have an option to specify a configuration file, that might helps.

**Comment by lgersman** [comment]
ok, and how do i define the plugin konfiguration for the plugin ?

**Comment by MoOx** [comment]
Using the plugin option http://cssnext.io/usage/#plugins

**Comment by MoOx** [comment]
Please use the gitter chat for support.
