### ISSUE TITLE
Install failed on caniuse-api

### ISSUE THREAD

**Issue by piotrkulpinski** [cssnext/cssnext#226]
Hi, I can't get past cssnext installation due to some issue with caniuse-api package.
I tried cssnext and postcss-cssnext packages and they both return this error:

https://www.dropbox.com/s/kx5f9ols9jp5f63/Screenshot%202015-10-18%2020.56.45.png?dl=0

**Comment by MoOx** [comment]
Please try again, should be fixed by caniuse-api 1.4.1

**Comment by piotrkulpinski** [comment]
Thanks for the quick fix! Now it's working.
