### ISSUE TITLE
:local + url(File) - unexpected behaviour

### ISSUE THREAD

**Issue by alexbyk** [cssnext/cssnext#228]
this works well
```
:local(.selectLocale) {
  background: url(SelectLocale72x72.png) no-repeat 90% #eee;
}
```

This (without brackets)
```
:local .selectLocale {
  background: url(SelectLocale72x72.png) no-repeat 90% #eee;
}
```
throws an error
```
ERROR in ./~/css-loader!./~/cssnext-loader!./src/components/SelectLocale.css
Module not found: Error: Cannot resolve module 'SelectLocale72x72.png'
```
That's a bug, right? Or I missed something?

**Comment by MoOx** [comment]
What is your error?

**Comment by alexbyk** [comment]
@MoOx Sorry, forgot to mention. Updated

**Comment by MoOx** [comment]
This is a css-loader error. Please read the doc carefullly. Note also that cssnext might update your url() if imported but it seems that not the cause of your issue.
