### ISSUE TITLE
postcss version, or how to combine media queries at the bottom

### ISSUE THREAD

**Issue by silenceisgolden** [cssnext/cssnext#232]
When I try to use `css-mqpacker` as a postcss plugin inside of cssnext, it throws an error

```
Your current PostCSS version is 4.1.16, but css-mqpacker uses 5.0.10. Perhaps this is the source of the error below.

events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: css.walkAtRules is not a function
```

A) any plans on upgrading postcss version in dependencies OR
B) how to accomplish grouping media queries at the bottom of the document and combining them into one for multiple of the same media query?

**Comment by MoOx** [comment]
Please look at #230

**Comment by silenceisgolden** [comment]
@MoOx Thanks for the response, I'll check that out.
