### ISSUE TITLE
is there a way to convert a cssnext input file into a sass input file?

### ISSUE THREAD

**Issue by davidmaxwaterman** [cssnext/cssnext#236]
I am working on a team that seems to use sass (as a drupal module). I don't know sass, and would like to dedicate my time to learning stuff that will (likely) become standard, and so I've been using cssnext (actually gulp-cssnext).
However, it seems that my work just ends up being converted into sass. It would make things a lot easier if there were a converter tool to convert my css custom properties and calc() calls into their sass equivalents. I guess it might help others switch too.
Anything like that?

aside: it looks like drupal needs to be able to run an actual command to run postcss-autoprefixer - I guess that might be a good argument for continuing to have a postcss version of cssnext that runs from the command line.

**Comment by MoOx** [comment]
I am not aware of something like that. Seems like going backward to me :/
But you can probably do that by making your own postcss plugin...

**Comment by davidmaxwaterman** [comment]
While I can see what you mean, but this is about being compatible and easing people into the new way.

Anyway, *I* wouldn't be able to make my own plugin because I would need to learn sass to do that, and I'm attempting to avoid that. If I had to do learn sass, then I might as well just write it in sass to start with...

From what I've seen, drupal needs it to be a command to run - does postcss have a command line version?

**Comment by MoOx** [comment]
Yes, see postcss-cli.
