### ISSUE TITLE
Browser support à la autoprefixer

### ISSUE THREAD

**Issue by MoOx** [cssnext/cssnext#32]
Using a list of browser version we should be able to enable/disable a feature.
Note: some feature might require some other (eg: if custom props are disabled (untouched), but color enabled, var() in color() won't be resolved & browser wont be able to resolve it too since color is unsupported (in this case)). Not sure this can happen, we will see how browsers implement stuff :/

Ref https://github.com/postcss/autoprefixer/issues/284

**Comment by MoOx** [comment]
FYI, this is done and ready.
But I need to fix this issue https://github.com/Nyalab/caniuse-api/issues/18 in order to have a browserify build that works (for the playground).

**Comment by Nyalab** [comment]
I take care of that very soon :smile_cat:
