### ISSUE TITLE
upgrade to postcss 4

### ISSUE THREAD

**Issue by MoOx** [cssnext/cssnext#55]
- get ride of .childs everywhere
- some new apis
- better errors

https://github.com/postcss/postcss/releases/tag/4.0.0

Plugins to update:
- [x] postcss-import
- [x] postcss-custom-properties
- [x] postcss-calc
- [x] postcss-custom-media
- [x] postcss-media-minmax
- [x] postcss-custom-selectors
- [x] postcss-color-rebeccapurple
- [x] postcss-color-hwb
- [x] postcss-color-gray
- [x] postcss-color-hex-alpha
- [x] postcss-color-function
- [x] postcss-font-variant
- [x] pleeease-filters
- [x] autoprefixer-core v5
- [x] csswring v3

**Comment by MoOx** [comment]
Everything is ready except pleeease-filters upgrade ([PR opened](https://github.com/iamvdo/pleeease-filters/pull/5)).

**Comment by jasonkuhrt** [comment]
How can I help get this out the door?

**Comment by MoOx** [comment]
I plan to do that tomorrow morning, should not be a big deal.
Otherwise, you can do that if you want it done before :)

**Comment by jasonkuhrt** [comment]
@MoOx I am working up a PR that will update deps and make sure all tests are passing. I have 8 failing tests, working my way down to 0 : )

**Comment by MoOx** [comment]
Stop it right now.It's done. Pushing.

**Comment by jasonkuhrt** [comment]
@MoOx ha cool ; )

**Comment by MoOx** [comment]
release will wait for postcss-url being integrated with tests now #57 :)

**Comment by jasonkuhrt** [comment]
@MoOx I'm going to try now.

**Comment by jasonkuhrt** [comment]
@MoOx Why don't we release a 0.7.0 now? Waiting for Autoprefixer right? @ai did that : ) https://github.com/postcss/autoprefixer/commit/64f087f405d9e6a9bd6214a41c3d38d074b9aac1

**Comment by MoOx** [comment]
I'm finishing #63 before 0.7

**Comment by MoOx** [comment]
Will release that tomorrow and bump all others packages.

**Comment by magsout** [comment]
:+1:

**Comment by MoOx** [comment]
@jasonkuhrt @magsout I'm not going to release a 0.7 and going to release 1.0 directly after #32 (I started working on that already). I think API & ABI are stable enough for a major release.
Maybe 1.0 will include #64 too.
Meanwhile, I think npm shrinkwrap might help to force current master for the tools you might use.

**Comment by MoOx** [comment]
If possible I would like to release 1.0 on friday (my birthday ^^).

**Comment by magsout** [comment]
heh, good to know ;)

**Comment by jasonkuhrt** [comment]
: )
