### ISSUE TITLE
add option to manipulate directly postcss (eg: to add custom plugins)

### ISSUE THREAD

**Issue by MoOx** [cssnext/cssnext#56]
use case: convenient way to manipulate postcss instance directly, for example to add postcss-url to adjust url according to a cdn via cssnext-loader options.
Ref https://github.com/cssnext/cssnext-loader/issues/3

**Comment by magsout** [comment]
>just add example on how to use cssnext via postcss to do that.

Better IMHO

**Comment by MoOx** [comment]
I added several times the fact that cssnext can be used as a postcss plugin.
