### ISSUE TITLE
Fix browser list (for test)

### ISSUE THREAD

**Issue by MoOx** [cssnext/cssnext#58]
Recent update to caniuse database make -webkit- off by default (related to default value of autoprefixer). So tests are currently broken (by a README update).

We need to handle #32 asap & get our custom default value.

Or maybe we should adjust default value for testing purpose ?

Or both.

**Comment by bloodyowl** [comment]
we need to support `-webkit-` prefixing by default IMO. lots of properties are still prefixed in current safari & various versions of android

**Comment by MoOx** [comment]
v1.0.0 will rely on browserslist, so you will easily be able to handle that by yourself.
I'm not even sure we should rely on a default value, but instead enforce people to specify their own value, maybe by importing their own browser stats like caniuse recommand.

I just opened a new issue about that on browserslist https://github.com/ai/browserslist/issues/4

**Comment by MoOx** [comment]
Well it's not really what I was thinking... https://github.com/postcss/autoprefixer/issues/381

**Comment by MoOx** [comment]
Ok I updated the tests to fix that issue. Not related to -webkit-transform directly but some other -webkit.
autoprefixer defaults are still relevant. So forget this issue.
