### ISSUE TITLE
Support for data structures and loops

### ISSUE THREAD

**Issue by benfrain** [cssnext/cssnext#60]
One thing I would miss moving to cssnext from Sass would be data structures (maps) and loops.

Maps reference in  Sass:
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#maps

Control directives and expressions reference in Sass:
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#control_directives__expressions

Obviously, I recognise that this is certainly in the bonus features section.

**Comment by MoOx** [comment]
CSS is not a programming language, so clearly -1 for if/else.
You might use (or not) some class in html/js as you need.

For the "DRY" part (maps/each...), you should follow where [this thread](https://github.com/postcss/postcss/issues/162) ends up.
cssnext can be used as a postcss plugin so you can chain cssnext with other postcss plugins.

That being said cssnext will only get w3c stuff to offer a code that is supposed to work (someday) in every browsers.
About bonus features
- import is working in browsers
- minification is "just" here to remove useless chars.

I don't see any other bonus feature that will be included in cssnext.

Sorry to now offer you a happy ending for this issue =)

**Comment by MoOx** [comment]
I will add that by writing modular code with a component approach, I do not feel the need of this features anymore.

**Comment by benfrain** [comment]
Really? How do you handle this kind of problem with cssnext:

http://benfrain.com/using-lists-with-maps-in-sass-3-3/

Generating 150 rules each with a slight variation (different border colours or background colours etc)

Is there some way of adding in custom JS functions to loop? Or would you just write it all 'long-hand'?

**Comment by MoOx** [comment]
I will handle this kind of case with a simple templating solution (understand here: I will use a real programming language that will generate css files for me).
I don't think you need the 150 variations in the same CSS file (on the same page), don't you ?

**Comment by MoOx** [comment]
Btw, you can totally write custom postcss plugin that will inject new CSS rules depending on some property/value sniffing. Check out postcss API for that :)

**Comment by benfrain** [comment]
@MoOx yes, in this case, I actually did. An extreme case but a real one! :)

For lesser mortals such as myself I think the combination of a pre (Sass) and post (Autoprefixer) gives me everything I need right now. My JS-fu is weak so I can accomplish everything I need this way. Thanks for the info and responses though.

**Comment by MoOx** [comment]
(even if you did need that in the same file, you can do that with templating).

I understand that Sass + autoprefixer make a lot of people happy enough to don't need anything else.

But I want to write future-proof code today, like when I write es6 :)

**Comment by ahmedelgabri** [comment]
@MoOx I'd be interested to see an example using templating & CSS to handle a situation like this if you can.

**Comment by MoOx** [comment]
```js
var output = ""
[{
  name: "sky",
  image: "blue-sky.jpg",
  background: "blue"
},
{
  name: "night",
  image: "night.jpg",
  background: "#BADA22"
}].forEach(h => output += `.Header--${name} {background: ${h.background} url(${h.image});}\n`)

require("fs").writeFileSync("headers.css", output)
```
Note: es6 with arrow function & template string. Should work in iojs natively or using 6to5-node :) (or with node --harmony maybe

**Comment by ahmedelgabri** [comment]
@MoOx Thanks.

I understand the idea behind CSSnext is to be future friendly and follow the spec, but some kind of support for this will be useful, not in core ofcourse but maybe as an official plugin. I'm not a big fan of crazy logic inside CSS but some basic logic can be helpful.

From a maintainability point of view, now you need to maintain two files written in two languages (JS & CSS), if I understand correctly. Which is not ideal.

Maybe I'm missing something here, so if you can point me to any information/articles/etc... on postprocessors workflows especially in large teams it'll be great.

**Comment by MoOx** [comment]
@ahmedelgabri cssnext can be used as a postcss plugin, so you can totally chain it with some other plugins you want.

I don't have any good links to share yet. But I've to admit I just get one use case for this kind of templating in 2014. So didn't look like a big deal to me :)
