### ISSUE TITLE
Disallow webpack from using cssnext as a loader

### ISSUE THREAD

**Issue by jasonkuhrt** [cssnext/cssnext#61]
Basically this should *never* happen https://github.com/webpack/webpack/issues/725#issuecomment-71663236!

**Comment by MoOx** [comment]
Note sure we can handle in cssnext, since webpack probably try module as a simple function (cssnext is such a function, that take a string as first param).
This should be handled in webpack probably...

**Comment by MoOx** [comment]
I am open to do something, but why... I've no idea.

**Comment by jasonkuhrt** [comment]
> This should be handled in webpack probably...

@sokra agree?

**Comment by sokra** [comment]
I can imaging no non-breaking webpack change which would fix this, but I schedule a breaking change for 2.0...

You can add this to cssnexts package.json:

``` js
  "loader": "this is not a loader"
```

**Comment by MoOx** [comment]
Maybe more something like

```js
  "webpack": {
    "loader": "cssnext-loader" // then this warn user about using the appropriate loader
  }
```

**Comment by jasonkuhrt** [comment]
Hurray for untyped languages. @stresslimit

**Comment by sokra** [comment]
@MoOx This is supported, but it's only `"loader": "cssnext-loader"`

**Comment by MoOx** [comment]
adding a "loader" key in a package.json with the name of the real loader to use warn the user ? That would solve the issue then... What did I miss ?

**Comment by MoOx** [comment]
@sokra do you confirm that adding `"loader": "cssnext-loader"` in package.json in `cssnext` package will make webpack look for `cssnext-loader` and throw an error if this package is missing?

**Comment by sokra** [comment]
Actually I think `"loader": "cssnext-loader"` is like `"loader": "./cssnext-loader"` and try to resolve to a file in the package. It works like the `"main"` field.

**Comment by MoOx** [comment]
Nobody has got the same issue, so I am closing.

**Comment by MoOx** [comment]
Someone just get the same issue, I will make something to avoid this again.

**Comment by bloodyowl** [comment]
how about a `npm_loader` field, @sokra ?

**Comment by iam4x** [comment]
(full disclosure: I'm the culprit)

**Comment by iam4x** [comment]
Great job @MoOx thank's :+1:
