### ISSUE TITLE
Relocate `import` in API (not as a `feature` anymore)?

### ISSUE THREAD

**Issue by MoOx** [cssnext/cssnext#63]
Since ﹫import integration is sort of a bonus feature (like its new friend postcss-url), maybe we should move that out of the features list.
Like minification (via `compress` option), I think we should have `import` and `url`, not with all `features`. 

With #32, features will be enabled/disabled according to the browsers scope so it doesn't make sense to keep those features into the `features` list (yes this sentence is funny).

**Comment by magsout** [comment]
+1
