### ISSUE TITLE
Found a way to emit messages (error/warning)

### ISSUE THREAD

**Issue by MoOx** [cssnext/cssnext#64]
Currently some postcss plugins report some errors/warning using `console`.

When you got something like webpack-dev-server, it's just horrible to debug.
Sometimes you don't even see those messages, not sure why.

We need to add to all plugins that throw messages the ability to adjust what to use to handle errors & warnings.

We can
- throw some errors in plugins then handle the exceptions, but some people where not happy with that
- provide a callback to handle messages like webpack does: `emitWarning` & `emitError` (default to `console.warn` & `console.error`)

Ideas?

**Comment by MoOx** [comment]
Since this "feature" will not bring any breaking change, I am going to release 1.0 without that because I think it's better to bring new APIs first in PostCSS.
Here is a issue for that https://github.com/postcss/postcss/issues/177

**Comment by MoOx** [comment]
postcsss 4.1 is out with the requested API. We "just need" to update all plugin that output warning and stuff.

**Comment by magsout** [comment]
Let's GO

**Comment by MoOx** [comment]
Closing in favor of #88
