### ISSUE TITLE
Cannot read property 'type' of undefined when file has :root

### ISSUE THREAD

**Issue by johanalkstal** [cssnext/cssnext#67]
I have two files,

`// style.css`
```
@import "variables.css";

.blue {
    color: blue;
}
```
`// variables.css`
```
:root {
    --color: white;
}

.red {
    color: red;
}
```

Running `cssnext style.css` does not work.

```
Cannot read property 'type' of undefined
    at C:\Users\johan_000\AppData\Roaming\npm\node_modules\cssnext\node_modules\pixrem\lib\pixrem.js:34:20
    at C:\Users\johan_000\AppData\Roaming\npm\node_modules\cssnext\node_modules\postcss\lib\container.js:189:30

    at C:\Users\johan_000\AppData\Roaming\npm\node_modules\cssnext\node_modules\postcss\lib\container.js:124:26

    at Root.each (C:\Users\johan_000\AppData\Roaming\npm\node_modules\cssnext\node_modules\postcss\lib\container.js:102:22)
    at Root.eachInside (C:\Users\johan_000\AppData\Roaming\npm\node_modules\cssnext\node_modules\postcss\lib\container.js:123:21)
    at Root.eachRule (C:\Users\johan_000\AppData\Roaming\npm\node_modules\cssnext\node_modules\postcss\lib\container.js:187:21)
    at Pixrem.postcss (C:\Users\johan_000\AppData\Roaming\npm\node_modules\cssnext\node_modules\pixrem\lib\pixrem.js:33:7)
    at PostCSS.process (C:\Users\johan_000\AppData\Roaming\npm\node_modules\cssnext\node_modules\postcss\lib\postcss.js:70:28)
    at cssnext (C:\Users\johan_000\AppData\Roaming\npm\node_modules\cssnext\index.js:132:26)
    at C:\Users\johan_000\AppData\Roaming\npm\node_modules\cssnext\bin\cssnext:73:17
```

But if I remove `:root { }` from the imported file, it works.

```
λ cssnext style.css
/*:root {*/
    /*--color: white;*/
/*}*/

.red {
    color: red;
}

.blue {
    color: blue;
}
```

Why?

**Comment by MoOx** [comment]
2 bugs in one :)
One plugin doesnt keep ast clean by not providing a proprr parent property (probably postcss-import) and pixrem is calling a prop on a value that can be undefined. I will  take a look to both.

Thanks for reporting!

**Comment by MoOx** [comment]
@ai do you change anything related to removeSelf() in latest release ?
This bug seems to happen because the :root removal https://github.com/postcss/postcss-custom-properties/blob/604168e4e28379c3a42c8a8255957a65ec6b2c27/index.js#L67-L70

If you take the example provided above, you can try this in your console:

```
node -e 'console.log(require("cssnext")().process(require("fs").readFileSync("style.css"))'
```

To debug I used this

```
node -e 'console.log(require("cssnext")({features: {rem: false}).process(require("fs").readFileSync("style.css")).root.nodes[0].parent)'

// undefined
```

Here you will have undefined. If you disable customproperties, you do have a parent since the node has not been touched yet.

```
node -e 'console.log(require("cssnext")({features: {customProperties: false, rem: false}).process(require("fs").readFileSync("style.css")).root.nodes[0].parent)'

// [Object]
```

Is this related to the fix for https://github.com/postcss/postcss/issues/196 ?

**Comment by MoOx** [comment]
Closed by https://github.com/postcss/postcss-import/commit/7b5fa01a764eeef7939668d0c0b5380ba16d2b09

Responsible was postcss-import v5.0.2, 5.0.3 fixes this bug.

Please uninstall and reinstall cssnext to benefit of this patch automatically (via npm, semver will do the job for us)
