### ISSUE TITLE
`cssnext --watch` exits when there is an error

### ISSUE THREAD

**Issue by madx** [cssnext/cssnext#68]
If in launch `cssnext` with the `--watch` option and if there is an error in my source CSS, the whole process crashes because of the thrown exception and I have to launch it again from the command line.

IMO it would be much more useful to continue waiting for changes so the user has the opportunity to fix his mistakes without having to relaunch `cssnext`.

**Comment by MoOx** [comment]
Good idea. PRs are welcome ;)
