### ISSUE TITLE
Do you need postcss-will-change

### ISSUE THREAD

**Issue by ai** [cssnext/cssnext#70]
I wrote [postcss-will-change](https://github.com/postcss/postcss-will-change) as polyfill to `will-change` property. Unfortunately, it is not ideal, because it just insert `backface-visibility: hidden` before `will-change`. Backface visibility is safer that `transform` but anyway it can broke user styles in some rare cases.

But maybe it will be useful in cssnext?

**Comment by MoOx** [comment]
How the backface trick is helping to support `will-change` property ?

**Comment by ai** [comment]
It creates new composite layout. Absolutely like `will-change` does.

**Comment by MoOx** [comment]
Good. Any link to the specs about that ?

**Comment by ai** [comment]
http://dev.w3.org/csswg/css-will-change/

**Comment by MoOx** [comment]
I understand your trick but not sure there is no side effect. What if someone want to use the backface of an element ?
I am pretty sure @tabatkins will tell us it's completely a crazy idea :)

**Comment by ai** [comment]
@MoOx yeap, I mentioned in first comment about side effectsof this polyfill.

But backface is needed only if you use 3D transformations. And with 3D transformations you doesn’t need `will-change`, because 3D transform creates composite layout.

**Comment by MoOx** [comment]
Nobody gave feedback about this so I am closing (this doesn't meant we will never see this in cssnext).

**Comment by ai** [comment]
:'(
