### ISSUE TITLE
strippable comments like sass

### ISSUE THREAD

**Issue by ShaggyDude** [cssnext/cssnext#76]
In sass you can do regular comments that don't get stripped but,
/* comment that is output */
single line comments that do get stripped from output,
// comment that is only in the source file

This is very handy and encourages longer comments in source that do not adversely affect final file size

**Comment by kud** [comment]
I must admit, I loved that in Sass.

**Comment by MoOx** [comment]
cssnext is only following CSS specs. If there is nothing about that I won't add anything in this direction.

That being said, remember that you have a `compress` option that is probably removing some comments (via csswring) if you care about filesize.

Note: do you know that you "can" use inline comments http://www.xanthir.com/b4U10 ?

**Comment by jackyon** [comment]
hm.. so sad that comments feature not included in cssnext, because i use postcss cli, and seems csswring is not working with postcss cli.  any soluction?
