### ISSUE TITLE
--watch didn't check for changes in imported files

### ISSUE THREAD

**Issue by MoOx** [cssnext/cssnext#78]
To get a serious --watch option, we should handle this. Or drop --watch.

**Comment by Paulmicha** [comment]
Similar issue : https://github.com/suitcss/preprocessor/issues/3 -> https://github.com/philipwalton/deep-watch ?

**Comment by MoOx** [comment]
We should plug a callback on postcss-import#onImport option to listen on every imported file.

**Comment by MoOx** [comment]
You can play with a WIP by doing `npm install cssnext/cssnext#watch-imported`.
There is still a minor issue related to the watcher https://github.com/paulmillr/chokidar/issues/258
