### ISSUE TITLE
Update caniuse-api to 1.3.1 so windows works

### ISSUE THREAD

**Issue by RGBboy** [cssnext/cssnext#84]
caniuse-api just added a fix that was breaking installation on windows. If the dependency on caniuse-api is updated to 1.3.1 cssnext will now work on windows. I can put a pull request together if you like.

**Comment by MoOx** [comment]
It's not required. npm caret `^` will install the fix automatically (semver ftw).
If you have the bug on your setup, just uninstalll & reinstall cssnext, your will get the fix automatically.
Thanks anyway ;)

**Comment by RGBboy** [comment]
You are right! I always thought the caret only installed patches, learn something new everyday. Thanks MoOx.
