### ISSUE TITLE
Add this tip maybe in the doc (if not already added)

### ISSUE THREAD

**Issue by kud** [cssnext/cssnext#85]
I've got lots of projects which require themselves other projects. I have the same folder/file convention naming in each of these project and it could create some non explicite conflicts. 

Why? Because I do that: `@import "views/index.css";`

cssnext can be lost if you do `@import "views/index.css";` in a submodule and in your module, you've already have `"views/index.css"`.

To fix it, you have to specify `./` like `@import "./views/index.css";`. It's maybe obvious for some of you but it could be added in the doc I think. What do you think?

**Comment by bloodyowl** [comment]
as it works just like npm, browserify & webpack (which rely on the same convention), I don't think this is necessary. moreover it is documented here https://github.com/postcss/postcss-import#postcss-import--

**Comment by MoOx** [comment]
`@import "views/index.css";` and `@import "./views/index.css";`  are just exactly the same, per CSS spec. Except if `views` is a module. But I think local files are resolved first.
If you want to do something, please first open a PR on postcss-import with tests to describe an eventual real issue.
