### ISSUE TITLE
Support cssnextrc

### ISSUE THREAD

**Issue by ooflorent** [cssnext/cssnext#87]
Babel does it and it is awesome. Doing so babel is able to share config through every 3rd party integration libraries.

So please, give us the ability to mimic this behavior with cssnext!

![](https://media3.giphy.com/media/12JzvQ2kUlccN2/200.gif)

**Comment by Nyalab** [comment]
:+1:
![](https://31.media.tumblr.com/7210a29fdf7fce29bf9ef96f0c6306cd/tumblr_inline_nf9bsuffBT1t3lpra.gif)

**Comment by MoOx** [comment]
Closing in favor of #73

**Comment by ooflorent** [comment]
My bad

**Comment by MoOx** [comment]
Please guys, express yourselves about the format you would like to have ;)
