### ISSUE TITLE
Add postcss-message to show postcss 4.1 message output ?

### ISSUE THREAD

**Issue by MoOx** [cssnext/cssnext#88]
Related to #64 

What do you think about that as an option?

https://github.com/postcss/postcss-messages

![](https://camo.githubusercontent.com/b0abb0db5d0b273d4335e02667e842b22175d0b7/687474703a2f2f706f73746373732e6769746875622e696f2f706f73746373732d6d657373616765732f73637265656e73686f742e706e67)

**Comment by magsout** [comment]
:+1:

**Comment by MoOx** [comment]
I will go for a custom skin by default with the logo/color of cssnext. Do you think it's a good idea ?

**Comment by magsout** [comment]
I think yes. We will see that the error is raised by cssnext

**Comment by MoOx** [comment]
Also for cli https://github.com/davidtheclark/postcss-log-warnings

**Comment by MoOx** [comment]
How does it look ?

![screen shot 2015-06-06 at 08 21 03](https://cloud.githubusercontent.com/assets/157534/8018599/45ebd13a-0c25-11e5-998c-fa65c4106941.png)

**Comment by magsout** [comment]
Woooot awesome.

**Comment by awayken** [comment]
Is cssnext actually parsing your error and suggesting an accurate fix for it? That's pretty cool.

Related to the error formatting: is it possible to use whitespace to better indicate the problem line and the corrected line?

Something like:
```
> cssnext:custom-selectors:missing-colon-fix: <css input>:1:30: Incorrect syntax for @custom-selector.

@custom-selector --h h1, h2;

Should be:

@custom-selector :--h h1, h2;
```

I also see the "Please adjust this..." sentence as maybe being unnecessary.

Anyway, those are just my 2¢ as a relative outsider who apparently has an opinion on this.

**Comment by MoOx** [comment]
My question was more for the design that the content itself.

That said, i will probably adjust messages with some newlines, that's a good idea.

For the record some plugin currently use console.log to talk to users (eg. postcss-custom-properties might warns you if you try to use an undefined var). Since it's not really users friendly (especially when you are using postcss in a verbose env like webpack) you might miss those log. That's why I asked this API for postcss.

This way we will be able to properly emit warnings in the appropriate way depending in the env (webpack, gulp, cli...) + in the css itself using the famous hack ::before/content.

**Comment by awayken** [comment]
That said, I really like the design. I know the blue complements the logo, but it has the side effect of being calming even in the midst of the potential frustrations of learning these new specs. Bonus!

**Comment by MoOx** [comment]
I think I will replace the logo by another icon: `{ ! }`

**Comment by MoOx** [comment]
Is this any better ?

![screen shot 2015-06-06 at 23 42 52](https://cloud.githubusercontent.com/assets/157534/8021594/c879b8f8-0ca5-11e5-81c1-b14bac323d4c.png)

**Comment by MoOx** [comment]
Or with more space ?

![screen shot 2015-06-06 at 23 46 44](https://cloud.githubusercontent.com/assets/157534/8021604/51245014-0ca6-11e5-8a3c-c01fd0374a57.png)

**Comment by awayken** [comment]
I like them both. What's nice about the additional space is that it makes it easier to pick out individual issues if you miss the `> cssnext:`.

**Comment by MoOx** [comment]
Or with the icon in the top left corner

![screen shot 2015-06-07 at 14 37 33](https://cloud.githubusercontent.com/assets/157534/8023973/cb5a398a-0d22-11e5-8311-993d968b0b2b.png)

**Comment by awayken** [comment]
I like that better.

**Comment by MoOx** [comment]
I will go for a simpler icon

Which one ?

![screen shot 2015-06-08 at 09 16 16](https://cloud.githubusercontent.com/assets/157534/8029585/2d45e990-0dbf-11e5-80b5-28335795009e.png)
![screen shot 2015-06-08 at 09 16 24](https://cloud.githubusercontent.com/assets/157534/8029586/2d4bef20-0dbf-11e5-9e01-0458c3f24c3f.png)
![screen shot 2015-06-08 at 09 16 29](https://cloud.githubusercontent.com/assets/157534/8029587/2d4ed4b0-0dbf-11e5-82bc-67f12d37e8f3.png)

**Comment by madx** [comment]
I vote for the second one: being filled makes it more visible, and it keeps the shape of the `{!}` logo

**Comment by bloodyowl** [comment]
first one IMO

**Comment by madx** [comment]
The downside being that it looks like and information instead of a warning/error :/

**Comment by MoOx** [comment]
Note that we might have here info/debug message in the future.

**Comment by kud** [comment]
I prefer the third one, but the second one is quite ok and mostly efficient. So the 2nd one. The first one is "an error", not a notice.

**Comment by awayken** [comment]
I like the third one best. Second favorite is the second one.

**Comment by awayken** [comment]
Updated the project I'm using cssnext on to see how this works in practice, and I love this feature so much.

**Comment by MoOx** [comment]
Glad you enjoy it.
