### ISSUE TITLE
Add support for rgba fallback as hexa for IE < 9

### ISSUE THREAD

**Issue by MoOx** [cssnext/cssnext#89]
https://github.com/TrySound/postcss-color-hex

**Comment by MoOx** [comment]
http://caniuse.com/#feat=css3-colors

**Comment by magsout** [comment]
We need to create a new plugin ?

postcss-color-hex-alpha transforms RGBA hexadecimal notation to rgba, but it missed postcss-color-rgba witch transforms RGBA to rgb, no ?

**Comment by MoOx** [comment]
yeah

**Comment by MoOx** [comment]
Closed in favor of #95
