### ISSUE TITLE
Weird bug, can't explain it in the title yet

### ISSUE THREAD

**Issue by kud** [cssnext/cssnext#92]
I have two modules which have the same folder structure.

Both have also an `index.css` in the root, which does:

```css
@import './src/style/index.css'
```

If I do in my main project: 

```css
@import 'module-a';
@import 'module-b';
```

It will only import the first line. If I switch the lines, it will import so `mobule-b` but not `module-a`, always the first line.

The workaround is to do that:

```css
@import 'module-a/src/styles/index.css';
@import 'module-b/src/styles/index.css';
```

This works.

(Be sure this one doesn't work too:

```css
@import 'module-a/index.css';
@import 'module-b/index.css';
```
)

I need to inspect why, I just wanted to create the bug first and will be back when I've got more news.

Cheers.

**Comment by MoOx** [comment]
Explanation is here https://github.com/postcss/postcss-import/issues/31#issuecomment-88735346
Closing in favor of this linked issue.
I will try to handle that. Remember that PR are always welcome.
