### ISSUE TITLE
Consider switching compressor

### ISSUE THREAD

**Issue by MoOx** [cssnext/cssnext#94]
https://github.com/ben-eb/cssnano

**Comment by MoOx** [comment]
Or maybe we should just get rid of the compressor in cssnext.

**Comment by magsout** [comment]
it's more a clone of cssnext than a compressor ?

**Comment by MoOx** [comment]
Humm not from what i see in the first place. Only postcss-calc looks duplicated.

**Comment by magsout** [comment]
you're right. There are many optimization, code cleanup. So why not. 

What's your idea ?  Only use instead of `csswring` with all the options that seem interesting to activate by default? Or give the possibility to configure the options?

**Comment by MoOx** [comment]
All of that? :)

**Comment by magsout** [comment]
lol ok :+1:

**Comment by magsout** [comment]
Two things:
- options like `sourcemap`, `calc`, and `urls` are disabled by default? cssnext already using its function.
- If I look at the documentation I see no option to disable the `postcss-pseudoelements` option, which is not great for cssnext

**Comment by MoOx** [comment]
Maybe @ben-eb can helps us on that ?

**Comment by ben-eb** [comment]
Sure; the architecture is similar to cssnext in that you can disable processors, although some of those I opted to not disable as they are safe optimisations. e.g since postcss-pseudoelements v2, the single colon syntax of before and after is supported across all browsers so is safe to minify.

Of course, I can add the option to disable these if you would like.

**Comment by MoOx** [comment]
It's not necessary since we are using this plugin only to ensure ie8 compat (so if IE 8 is not in the scope, we won't enable it).
Your arguments looks good enough for me. Thanks.

**Comment by magsout** [comment]
@MoOx 
>It's not necessary since we are using this plugin only to ensure ie8 compat (so if IE 8 is not in the scope, we won't enable it).

yes, but `cssnext` consume `cssnano` after, so if IE 8 is not in the scope, `cssnano` doesn't matter and manage selector like after: and before: ?

And what do you think about `sourcemap` , `calc` ? We let users enable or disable those features ?

**Comment by ben-eb** [comment]
@MoOx @magsout I think you are better to wait until this attribute selector bug is fixed before you migrate. :smile:

https://github.com/ben-eb/postcss-minify-selectors/issues/2

**Comment by MoOx** [comment]
@magsout you write `::`. If the compression convert to `:` do you really care ? I don't think you should since you asked for the smallest possible size :)
`sourcemap` will need to be adjusted according to cssnext value.
`calc` should be disabled indeed.

**Comment by magsout** [comment]
LGTM
