### ISSUE TITLE
Inline sourcemap not working

### ISSUE THREAD

**Issue by teddybradford** [cssnext/cssnext#96]
I'm using Gulp to run a task that processes my CSS through PostCSS with the cssnext plugin. Here's the task config:

```js
gulp.task('styles', function () {
  var source = paths.src + 'styles/index.css';
  return gulp.src(source)
    .pipe(postcss([
      cssnext({
        browsers: 'last 2 versions',
        features: {
          rem: false
        },
        sourcemap: true,
        from: source
      })
    ]))
    .pipe(gulp.dest(paths.dest))
});
```

My `index.css` file has a bunch of `@import` lines, making use of the postcss-import feature included in cssnext.

Unfortunately, the resulting CSS file outputted by the Gulp task has no inline sourcemap at the end of it. Any idea why?

**Comment by MoOx** [comment]
The thing is cssnext is not just a postcss plugin. You can use it directly and that the main goal of this tool. That why some options are just proxies to postcss options. (also, you can use gulp-cssnext)
In your case I think you should pass sourcemap & from to postcss directly.

Btw why are your using rem: false when your browser scope do not target old IEs ?

**Comment by teddybradford** [comment]
Thanks! That helped me figure out where to look to get sourcemaps working. The `gulp-postcss` package has [sourcemaps disabled by default](https://github.com/w0rm/gulp-postcss#source-map-support).

`rem: false` disables the `px` unit fallback, which I don't require for my project. The last 2 versions of IE can use REM [except when used in the font shorthand property or in pseudo elements](http://caniuse.com/#feat=rem).
